theme = "autumn"

[editor]
true-color = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
# select = "underline"

[keys.normal]
F8 = ":open ~/.config/helix/config.toml"
Z = { Z = ":wq", Q = ":q!" }
"space" = { w = { i = ":wq" } }

[keys.insert]
C-p = "move_line_up"
C-n = "move_line_down"
C-b = "move_char_left"
C-f = "move_char_right"
C-a = "goto_line_start"
C-e = "goto_line_end_newline"
# k = { j = "normal_mode" } # Maps `kj` to exit insert mode
