theme = "autumn"

[editor]
true-color = true

[editor.cursor-shape]
normal = "block"
insert = "bar"
# select = "underline"

[keys.normal]
K = ["move_line_up", "move_line_up", "move_line_up", "move_line_up", "move_line_up"]
J = ["move_line_down", "move_line_down", "move_line_down", "move_line_down", "move_line_down"]
Q = ":q"

F8 = ":open ~/.config/helix/config.toml"
Z = { Z = ":wq", Q = ":q!" }

[keys.normal.space.q]
Q = "record_macro"

[keys.normal.space.w]
i = ":wq"
u = ":update"

[keys.insert]
C-p = "move_line_up"
C-n = "move_line_down"
C-b = "move_char_left"
C-f = "move_char_right"
C-a = "goto_line_start"
C-e = "goto_line_end_newline"
# k = { j = "normal_mode" } # Maps `kj` to exit insert mode
