[[language]]
name = "toml"
auto-format = true

[[language]]
name = "move"
scope = "source.move"
injection-regex = "move"
file-types = ["move"]
roots = ["Move.toml"]
comment-token = "//"
language-server = { command = "move-analyzer" }
indent = { tab-width = 4, unit = "    " }

[[grammar]]
name = "move"
source = { git = "https://github.com/move-hub/tree-sitter-move", rev = "93527b2c4845293384759e8ebee8fdd8a0878ad8" }

[[language]]
name = "javascript"
auto-format = true
